### ISSUE TITLE
Doesn't seem to work

### ISSUE THREAD

**Issue by LukeTheGit** [kravock/php-cba-netbank#1]
Hi there,

I've added the api call section of code to the main block and run it. It seems to do some working, but then I receive this error:
Notice: Undefined offset: 0 in C:\xampp\htdocs\php-cba-netbank-master\src\API.php on line 234

It seems the $accounts array is returned empty. Not sure why this is, and I am too crap at PHP to debug. Perhaps it means it doesn't work?

**Comment by andrewbroberg** [comment]
Hey mate, can you provide me a full stack trace of the error? Make sure to remove your credentials if they are showing. 

This code hasn't been touched for a long time so may be broken. I have just tried on Mac and I am able to pull in my account list fine.

**Comment by andrewbroberg** [comment]
Actually looks like I need to update the docs.

If you print_r($accounts) you will see the index of each is the bsb + account number. You'll need to access the index of the accounts.

I've also pushed a new version with a fix for the getting transaction page. Let me know how you go now.

**Comment by LukeTheGit** [comment]
Hey Andrew,

Thanks for the reply.
The error that is thrown is from the last line of code and is the only thing shown with the following try-catch:
try {
$api = new API();
$accounts = $api->login('username', 'password');
$accounts = $api->getTransactions($accounts[0], '01/04/2017', '22/12/2017');
} catch ( Exception $e ) {
   var_dump( $e->getTrace() );
}

I don’t get any of the other errors printed out such as 'Unable to retrieve account list.' There is only 1 bank account in the account I am using, and it does have transactions between those dates.

Keep in mind, I have no idea what I am doing – I’m a data analyst interested in extracting the data programmatically, not a dev looking for some data... This is a bit of a hurdle for me :P

Cheers,

Luke


________________________________

**Comment by LukeTheGit** [comment]
Ah yes, that worked. I also needed to refer to the index as a string, otherwise I got ‘Invalid numeric literal<https://stackoverflow.com/a/40736053>.’
$accounts = $api->getTransactions($accounts["06294814224675"], '01/04/2017', '22/12/2017');

This works fine for my purposes – I am sure there is a better way!

Thanks for your prompt assistance, mate! Much appreciated.

Cheers,

Luke

________________________________

**Comment by andrewbroberg** [comment]
Yeah you'll need to use it as a string. Feel free to open another issue if you have further issues, I wouldn't be surprised if other things are broken!
