### ISSUE TITLE
does this still work?

### ISSUE THREAD

**Issue by rgogada** [kravock/php-cba-netbank#2]
Hi mate, does this still work? I heard CBA a has changed a few things, so not sure. I am getting the below error. please see if you could help. Thanks.

Fatal error: Uncaught Exception: Unable to retrieve account list. in /var/www/html/vendor/kravock/php-cba-netbank/src/API.php:71 Stack trace: #0 /var/www/html/scripts.php(264): Kravock\Netbank\API->login('xxxx', 'xxxxxx.') #1 {main} thrown in /var/www/html/vendor/kravock/php-cba-netbank/src/API.php on line 71

**Comment by andrewbroberg** [comment]
Hey mate, sorry for the slow reply. I haven't been maintaining this so not sure if it still works or not.

Feel free to open a pull request to fix it if you come across issues since changes CBA have made
